// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebApp.Models;

namespace MultiPageWebApp.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20201010175359_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiPageWebApp.Models.Contact", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            Address = "123 The Rock Ave",
                            Name = "Dwayne Johnson",
                            Note = "If you smell, what the rock is cook'n",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            PhoneId = 2,
                            Address = "1 Yankee Stadium St",
                            Name = "Derek Jeter",
                            Note = "Greatest shortstop of all time",
                            PhoneNumber = "222-222-2222"
                        },
                        new
                        {
                            PhoneId = 3,
                            Address = "18 Indianapolis Ln",
                            Name = "Peyton Manning",
                            Note = "Omaha!",
                            PhoneNumber = "181-181-1818"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
